# Generated by Django 4.0.5 on 2022-08-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
