# Generated by Django 4.0.5 on 2022-08-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='diagnoses',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='medications',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.BooleanField(default=0),
        ),
    ]
