# Generated by Django 4.0.5 on 2022-08-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_allergies_profile_diagnoses_profile_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=170.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=60.0),
        ),
    ]
