# Generated by Django 4.0.5 on 2022-08-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_height_profile_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Not set'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default='Not set'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postalcode',
            field=models.CharField(default='XXXXXX', max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.TextField(default='Note set'),
        ),
    ]
