# Generated by Django 4.1 on 2022-08-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_profile_address_profile_city_profile_postalcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upcoming',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.TextField(default='Not set'),
        ),
    ]
